### ISSUE TITLE
[FIXED]: http: ContentLength=N with Body length 0

### ISSUE THREAD

**Issue by eric-chao** [last-ent/distributed-go#3]
CODE in chapter8:
Location: 
github.com/distributed-go/src/chapter8/goophr/concierge/api/query.go

Line99: 
stBytes := bytes.NewBuffer(st)

Move To [ for loop body ]:

	for _, le := range librarianEndpoints {
		func(endpoint string) {
			stBytes := bytes.NewBuffer(st)
			go queryLibrarian(endpoint, stBytes, resultsCh)
		}(le)
	}

to avoid the "http: ContentLength=N with Body length 0"

coz Do() func will close the req body.

**Comment by last-ent** [comment]
Hi @eric-chao , thank you for pointing out the issue. 

I have updated the code to fix it but took a slightly different route, reason being that even with your suggested code fix the issue still pops up occasionally. I have closed the issue since the latest merge should fix it, if you still see any issues let me know and I will work on it.

Thank you for taking time to pick my book and working through it. Hope you found it enjoyable & learned something new :)
